# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxSwiftFirebaseSampleApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxSwiftFirebaseSampleApp

  target 'RxSwiftFirebaseSampleAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RxSwiftFirebaseSampleAppUITests' do
    # Pods for testing
  end

pod 'Firebase/Analytics'
pod 'RxCocoa'
pod 'RxSwift'

end
